### ISSUE TITLE
[Question] How retransmits are handled?

### ISSUE THREAD

**Issue by alxchk** [networkprotocol/reliable.io#4]
Hi Glenn!

I read source, and I can't get the way retransmits are handled.
Let's say we have next situation. A send to B single packet, which is dropped during transmission.
A -[DATA1]-XXXXX (missing)-> B
Because B miss this packet, it will never send ACK to A (or any other thing).

How A should resolve this situation?
Likely there should be some timer, which should retransmit non-ACKed packets after some time.
Like (simplified):

```
while (reliable_endpoint_pending(endpoint)) {
   sleep(reliable_endpoint_wait_for_ack_timeout(endpoint));
   if (reliable_endpoint_pending(endpoint)) 
       reliable_endpoint_retransmit(endpoint);
}
```

Or am I missing something?

**Comment by Ohmnivore** [comment]
I was looking for the same thing.

Eventually I realized that reliable.io doesn't have a re-transmission strategy, it's left up to the user to implement one in their desired manner.

yojimbo (which uses reliable.io) does just that. I believe it simply re-transmits un-acked packets at a certain rate (100ms by default) until they are acked.

I'm not sure what happens if a packet is never acked. Consider Host A and Peer B:

- Host A sends 30 packets per second to Peer B
- Host A re-transmits at a rate of 0.1s
- Peer B sends back 32 acks also at 30 packets per second
- Packet loss is 10%

A packet is included in Peer B's acks for 32/30 seconds or roughly 1s. During which time it can be re-transmitted 1s/0.1s = 10 times.

If this packet for some reason never reaches Peer B within this time window despite the 10 re-transmissions (odds are very low at 0.1^10), it will never again be included in an ack. There are more factors involved that I haven't included, and some network conditions can make this probability much higher - though you wouldn't really expect a realtime game to work with such conditions anyway.

I haven't checked if yojimbo just keeps re-sending this packet forever or if it detects it and disconnects the peer. I think that at one point this packet is removed from the circular "sent packets" buffer, at which point yojimbo detects the situation and disconnects the offending peer.

Again, this is all just my understanding. I might be wrong.

**Comment by alxchk** [comment]
Just FYI, nice interface for the same problem - [KCP](https://github.com/skywind3000/kcp)

**Comment by gafferongames** [comment]
Confirmed. There are no retransmits. reliable.io is a system that tells you which packets were received by the other side, it is up to you to decide if that means you have to do transmits.

If you want something that does transmits for you, try https://github.com/networkprotocol/yojimbo

It builds a reliable-ordered message channel concept on top of reliable.io, but in a different, more nuanced way than is normally done.

cheers

**Comment by gafferongames** [comment]
> I haven't checked if yojimbo just keeps re-sending this packet forever or if it detects it and disconnects the peer. I think that at one point this packet is removed from Host A's circular "sent packets" buffer, at which point the host detects the situation when trying to re-transmit it and disconnects the offending peer.

The reliable.io ack system guarantees that if you receive an ack for a packet it was receive, but it does not guarantee that all acks get through, it just gives you a *very high probability* that you get most acks. Basically, you only miss acks if no packets for 1/2 or 1 second, and at this point, you have bigger problems IMO (eg. an unplayable game...)

Yojimbo does not disconnect on missing acks, worst case it just resends something it didn't really need to, but everything works out. Only case where yojimbo disconnects is if you overflow the send queue for a reliable-ordered channel, which shouldn't happen (and you can ask if there is room to send a message).

cheers
