### ISSUE TITLE
test_packets()

### ISSUE THREAD

**Issue by mreinstein** [networkprotocol/reliable.io#5]
I'm looking at the`test_packets()` https://github.com/networkprotocol/reliable.io/blob/master/reliable.c#L1959

Is it fair to characterize this test as mostly about validating packet fragementation/reassembly?

**Comment by gafferongames** [comment]
Yes precisely, although it looks like it's not actually testing anything, just exercising that codepath.

**Comment by gafferongames** [comment]
Oh wait, it is testing stuff, because the test context creates packets with a particular pattern, which is asserted on when they are received, thus testing that the packets are reassembled correctly.

However, it would be nice if the loop had a condition that it has received n packets before exiting.

**Comment by mreinstein** [comment]
I guess having audited the code, one of my few bits of feedback would be to name this test more specifically. Pretty minor though. As usual your code is super tight! 👍
