### ISSUE TITLE
documentation/logic questions

### ISSUE THREAD

**Issue by mreinstein** [networkprotocol/reliable.io#7]
@gafferongames in working on a javascript port, I was going through the code in this library. It's so well written that I could follow along very easily. Very refreshing!

There are 3 areas where there is a little head scratching:

1.
I suspect this code has to do with handling very rare cases of extreme packet loss with sequence buffer wrap around:
https://github.com/networkprotocol/reliable.io/blob/master/reliable.c#L249-L256

2.
similarly, there's some logic in `_remove_entries which is a little confusing:
https://github.com/networkprotocol/reliable.io/blob/master/reliable.c#L207-L226

3.
It's not clear to me what the `_with_cleanup` variants of sequence buffer insertion/removal are for
https://github.com/networkprotocol/reliable.io/blob/master/reliable.c#L264
https://github.com/networkprotocol/reliable.io/blob/master/reliable.c#L264

I think comments in here about what these little bits are would be _immensely_ helpful. Everything else makes total sense.

Thanks again for a great codebase!

**Comment by mreinstein** [comment]
oh there's 2 more that are a little confusing.

4.
the `sequence_difference` variable, and it's affecting the packet header:
https://github.com/networkprotocol/reliable.io/blob/master/reliable.c#L667-L679

5.
there's mention of a 28 byte/48 byte packet header but I don't know how those numbers add up or see it referenced anywhere else in the code:
https://github.com/networkprotocol/reliable.io/blob/master/reliable.c#L538

**Comment by gafferongames** [comment]
1. This is code to reject stale packets, eg. packets that are older than the current sliding window in the sequence buffer.

2. This code is to remove entries as we advance the sequence buffer, eg. removing old entries that are outside the sliding window. I wrote it in a bit of a weird way to handle wrap around for the sequence #, without having to deal with signed modulus, hence the + 65535... but I think that's actually a bug. Shouldn't it be + 65536!?

3. The "_with_cleanup" variants are necessary to handle extreme packet loss. What happens is that for sequence buffers that have holes (eg. received packets, but not sent packets), if you don't advance with cleanup, you can have stale entries, thet once you wrap around, cause spurious acks, which breaks any reliability system built on top of reliable.io (speaking from experience, it broke yojimbo...)

4. This is an optimization. If the difference between the ack and the most recent received sequence # is small, we can encode it with fewer bits. There is also another optimization here if the acks are 100%, then we send just one bit, instead of 32bit 0xFFFFFFFFF

5. This is just an approximation of the actual on-the-wire header sizes for IP+UDP headers, on IPv4  and IPv6, respectively, for bandwidth estimation purposes.

**Comment by gafferongames** [comment]
Let me know if you have any other questions. ps. 100% sure the + 65535 is a bug... I'll go fix that now...

**Comment by gafferongames** [comment]
Fixed in 661b1843004a0fc470b2f5a964fc8a60a533ca0a

**Comment by mreinstein** [comment]
thanks for the clarifications! I've pulled in your sequence wraparound bugfix as well https://github.com/mreinstein/reliable.io.js/commit/eb762c8af55d9425901a9be1c86cb256f19e9fdc
